spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: update
              create-target: src/main/resources/sql/my-schema.sql