create table artist (id bigint not null, bio varchar(2000), date_of_birth date, email varchar(255), fist_name varchar(255) not null, last_name varchar(255) not null, primary key (id));
create table t_address (id bigint not null, street1 varchar(255), street2 varchar(255), primary key (id));
create table t_book (id bigint not null, description varchar(255), illustrations boolean, isbn varchar(255), nb_of_pages integer, price float4, title varchar(255), primary key (id));
create table t_city (city varchar(255), state varchar(255), zipcode varchar(255), city_id bigint not null, primary key (city_id));
create table t_country (country varchar(255), country_id bigint not null, primary key (country_id));
create table t_new (id bigint not null, language varchar(255) not null, content varchar(255), primary key (id, language));
alter table if exists t_city add constraint FK8a66c47tt6dwujmvlrdxrwp7b foreign key (city_id) references t_address;
alter table if exists t_country add constraint FKoc2hu83n580q05ee94nc2wv9c foreign key (country_id) references t_address;
alter table if exists t_book alter column price set data type float4;
create table t_new2 (language varchar(255) not null, id bigint not null, content varchar(255), primary key (id, language));
create table track (id bigint not null, description varchar(255), duration float4, title varchar(255), wav oid, primary key (id));
create sequence track_seq start with 1 increment by 50;
alter table if exists t_book alter column description set data type varchar(2000);
alter table if exists t_book alter column price set data type float4;
alter table if exists t_book add column book_title varchar(255) not null;
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
create table artist (id bigint not null, bio varchar(2000), date_of_birth date, email varchar(255), fist_name varchar(255) not null, last_name varchar(255) not null, primary key (id));
create table book2 (id bigint not null, description varchar(2000), illustrations boolean, isbn varchar(255), nb_of_pages integer not null, price float4, book_title varchar(255) not null, primary key (id));
create table t_address (id bigint not null, street1 varchar(255), street2 varchar(255), primary key (id));
create table t_book (id bigint not null, description varchar(255), illustrations boolean, isbn varchar(255), nb_of_pages integer, price float4, title varchar(255), primary key (id));
create table t_city (city varchar(255), state varchar(255), zipcode varchar(255), city_id bigint not null, primary key (city_id));
create table t_country (country varchar(255), country_id bigint not null, primary key (country_id));
create table t_new (id bigint not null, language varchar(255) not null, content varchar(255), primary key (id, language));
create table t_new2 (language varchar(255) not null, id bigint not null, content varchar(255), primary key (id, language));
create table track (id bigint not null, description varchar(255), duration float4, title varchar(255), wav oid, primary key (id));
alter table if exists t_city add constraint FK8a66c47tt6dwujmvlrdxrwp7b foreign key (city_id) references t_address;
alter table if exists t_country add constraint FKoc2hu83n580q05ee94nc2wv9c foreign key (country_id) references t_address;
alter table if exists book2 alter column price set data type float4;
create table credit_card (id bigint not null, control_number integer, credit_card_type smallint check (credit_card_type between 0 and 2), expiry_date varchar(255), primary key (id));
create table customer (id bigint not null, creation_date timestamp(6), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), primary key (id));
alter table if exists t_book alter column price set data type float4;
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
create sequence credit_card_seq start with 1 increment by 50;
create sequence customer_seq start with 1 increment by 50;
alter table if exists book2 alter column price set data type float4;
alter table if exists credit_card alter column credit_card_type set data type varchar(255);
alter table if exists customer alter column creation_date set data type timestamp(6);
alter table if exists t_book alter column price set data type float4;
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
alter table if exists book2 alter column price set data type float4;
create table credit_card (id bigint not null, control_number integer, credit_card_type varchar(255) check (credit_card_type in ('VISA','MASTER_CARD','AMERICAN_EXPRESS')), expiry_date varchar(255), primary key (id));
alter table if exists customer alter column creation_date set data type timestamp(6);
alter table if exists t_book alter column price set data type float4;
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
alter table if exists book2 alter column price set data type float4;
alter table if exists customer alter column creation_date set data type timestamp(6);
alter table if exists t_book alter column price set data type float4;
create table tag (book2_id bigint not null, value varchar(255));
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
alter table if exists tag add constraint FKo0d326pshpfec1xvowkyev7gg foreign key (book2_id) references book2;
alter table if exists book2 alter column price set data type float4;
create table cd (id bigint not null, cover oid, description varchar(255), price float4, title varchar(255), primary key (id));
alter table if exists customer alter column creation_date set data type timestamp(6);
alter table if exists t_book alter column price set data type float4;
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
alter table if exists track add column cd_id bigint not null;
alter table if exists track add column position integer not null;
create sequence cd_seq start with 1 increment by 50;
alter table if exists track add constraint FK5cr4kjx4j9njw95htewv56fov foreign key (cd_id) references cd;
create table artist (id bigint not null, bio varchar(2000), date_of_birth date, email varchar(255), fist_name varchar(255) not null, last_name varchar(255) not null, primary key (id));
create table book2 (id bigint not null, description varchar(2000), illustrations boolean, isbn varchar(255), nb_of_pages integer not null, price float4, book_title varchar(255) not null, primary key (id));
create table cd (id bigint not null, cover oid, description varchar(255), price float4, title varchar(255), primary key (id));
create table credit_card (id bigint not null, control_number integer, credit_card_type varchar(255) check (credit_card_type in ('VISA','MASTER_CARD','AMERICAN_EXPRESS')), expiry_date varchar(255), primary key (id));
create table customer (id bigint not null, creation_date timestamp(6), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), primary key (id));
create table t_address (id bigint not null, street1 varchar(255), street2 varchar(255), primary key (id));
create table t_book (id bigint not null, description varchar(255), illustrations boolean, isbn varchar(255), nb_of_pages integer, price float4, title varchar(255), primary key (id));
create table t_city (city varchar(255), state varchar(255), zipcode varchar(255), city_id bigint not null, primary key (city_id));
create table t_country (country varchar(255), country_id bigint not null, primary key (country_id));
create table t_new (id bigint not null, language varchar(255) not null, content varchar(255), primary key (id, language));
create table t_new2 (language varchar(255) not null, id bigint not null, content varchar(255), primary key (id, language));
create table tag (book2_id bigint not null, value varchar(255));
create table track (id bigint not null, description varchar(255), duration float4, title varchar(255), wav oid, primary key (id));
create table track_map (cd_id bigint not null, title varchar(255), position integer not null, primary key (cd_id, position));
alter table if exists t_city add constraint FK8a66c47tt6dwujmvlrdxrwp7b foreign key (city_id) references t_address;
alter table if exists t_country add constraint FKoc2hu83n580q05ee94nc2wv9c foreign key (country_id) references t_address;
alter table if exists tag add constraint FKo0d326pshpfec1xvowkyev7gg foreign key (book2_id) references book2;
alter table if exists track_map add constraint FK7wxf4gnljng88jqvb3p32wytc foreign key (cd_id) references cd;
create table artist (id bigint not null, bio varchar(2000), date_of_birth date, email varchar(255), fist_name varchar(255) not null, last_name varchar(255) not null, primary key (id));
create table book2 (id bigint not null, description varchar(2000), illustrations boolean, isbn varchar(255), nb_of_pages integer not null, price float4, book_title varchar(255) not null, primary key (id));
create table cd (id bigint not null, cover oid, description varchar(255), price float4, title varchar(255), primary key (id));
create table credit_card (id bigint not null, control_number integer, credit_card_type varchar(255) check (credit_card_type in ('VISA','MASTER_CARD','AMERICAN_EXPRESS')), expiry_date varchar(255), primary key (id));
create table customer (id bigint not null, creation_date timestamp(6), date_of_birth date, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), primary key (id));
create table t_address (id bigint not null, street1 varchar(255), street2 varchar(255), primary key (id));
create table t_book (id bigint not null, description varchar(255), illustrations boolean, isbn varchar(255), nb_of_pages integer, price float4, title varchar(255), primary key (id));
create table t_city (city varchar(255), state varchar(255), zipcode varchar(255), city_id bigint not null, primary key (city_id));
create table t_country (country varchar(255), country_id bigint not null, primary key (country_id));
create table t_new (id bigint not null, language varchar(255) not null, content varchar(255), primary key (id, language));
create table t_new2 (language varchar(255) not null, id bigint not null, content varchar(255), primary key (id, language));
create table tag (book2_id bigint not null, value varchar(255));
create table track (id bigint not null, description varchar(255), duration float4, title varchar(255), wav oid, primary key (id));
create table track_map (cd_id bigint not null, track_title varchar(255), position integer not null, primary key (cd_id, position));
alter table if exists t_city add constraint FK8a66c47tt6dwujmvlrdxrwp7b foreign key (city_id) references t_address;
alter table if exists t_country add constraint FKoc2hu83n580q05ee94nc2wv9c foreign key (country_id) references t_address;
alter table if exists tag add constraint FKo0d326pshpfec1xvowkyev7gg foreign key (book2_id) references book2;
alter table if exists track_map add constraint FK7wxf4gnljng88jqvb3p32wytc foreign key (cd_id) references cd;
alter table if exists book2 alter column price set data type float4;
alter table if exists cd alter column cover set data type oid;
alter table if exists cd alter column price set data type float4;
alter table if exists customer alter column creation_date set data type timestamp(6);
create table customer2 (id bigint not null, city varchar(255), country varchar(255), state varchar(255), street1 varchar(255), street2 varchar(255), zipcode varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), primary key (id));
create table customer3 (id bigint not null, email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(255), primary key (id));
create table customer3_address (customer3_id bigint not null, city varchar(255), country varchar(255), state varchar(255), street1 varchar(255), street2 varchar(255), zipcode varchar(255));
alter table if exists t_book alter column price set data type float4;
alter table if exists track alter column duration set data type float4;
alter table if exists track alter column wav set data type oid;
create sequence customer2_seq start with 1 increment by 50;
create sequence customer3_seq start with 1 increment by 50;
alter table if exists customer3_address add constraint FK50nhcjyupta1ax1polsy5m8rx foreign key (customer3_id) references customer3;
